[server]
port = 4567

[database]
driver = "mysql"
host = "localhost"
port = 3306
user = "root"
password = "root"
db = "gateway"
prefix = "t_"
showSql = true

[redis]
app="gateway"
host="localhost"
#password=""
port=6379
db=0
maxIdle=10
maxActive=100

[logger]
level = "debug"
maxSize = 10
backups = 7
maxAge = 30
compress = true
proxyTraceMaxSize = 1
proxyTraceMaxAge = 30
proxyBackups = 100

[task]
checkHealth = true